### ISSUE TITLE
Mobile scrolling bug

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/handbook#3666]
@lmelende20 reported an issue with the scrolling of handbook pages on mobile.
Example:
https://user-images.githubusercontent.com/88658267/171152709-3ef7cdf9-80eb-43de-a9e4-6e51599d0a82.MP4

The video is on the [homepage](https://handbook.sourcegraph.com/) on mobile and the issue is also on the [internship](https://handbook.sourcegraph.com/departments/people-talent/talent/internship/) page. 

[Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1653922913614959)

**Comment by nielthiart** [comment]
This is caused by the navigation height changing, which pushes content down on viewports below 900px. This causes a loop where a sub-menu repeatedly alternates between active/inactive.

Affects all pages with sidebar nav, and any viewport below 900px wide.

https://user-images.githubusercontent.com/154435/214257821-56967139-4d10-4289-acff-ab14bfa05926.mp4

**Comment by sqs** [comment]
@nielthiart Thank you for the PR!
